"""Initial migration.

Revision ID: dfddab7cb1a3
Revises: f905c058d350
Create Date: 2024-09-15 21:13:35.583379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfddab7cb1a3'
down_revision = 'f905c058d350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fruit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'fruit', ['fruit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fruit_id')

    op.drop_table('fruit')
    # ### end Alembic commands ###
