"""Initial migration.

Revision ID: f905c058d350
Revises: 7147936bd098
Create Date: 2024-09-15 16:06:49.839888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f905c058d350'
down_revision = '7147936bd098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('answer', sa.String(), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('answer')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
